"""The published eval report. Phase 7.5 step 1.

``web/public/report/index.html`` is generated by ``eval/report_page.py`` and committed. These tests hold
it to three things: it is what the generator produces now, it carries every section step 1 requires,
and the rules that keep a number honest -- N/A is never a pass, a judged number never travels without
its agreement, a gated verdict is one the gate actually made -- survive into HTML.

If the first test fails, run ``make report``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from musical_mycelium.eval import report_page
from musical_mycelium.eval.live import gate_record, write_result
from musical_mycelium.eval.suite import run_gold_suite
from musical_mycelium.eval.thresholds import NOT_APPLICABLE, GateOutcome, gate
from musical_mycelium.graph.memory import default_store


@pytest.fixture(scope="module")
def page() -> str:
    return report_page.render()


def test_the_committed_page_is_what_the_generator_produces(page: str) -> None:
    assert report_page.PAGE.read_text(encoding="utf-8") == page, (
        "web/public/report/index.html has drifted from eval/report_page.py -- run `make report`"
    )


@pytest.mark.parametrize(
    "section",
    ["live-gates", "scripted-gates", "metrics", "slices", "judged", "heldout", "did-not-work"],
)
def test_the_page_carries_every_section_step_1_requires(page: str, section: str) -> None:
    assert f'id="{section}"' in page


def test_a_not_applicable_gate_is_never_rendered_as_a_pass(page: str) -> None:
    """The free run leaves two gates untested. Each must say so in words, in its own row."""
    outcome = gate(run_gold_suite(default_store()))
    assert outcome.report is not None
    untested = [g for g in outcome.report.gates if g.verdict == NOT_APPLICABLE]
    assert untested, "the scripted run now decides every gate -- re-read what this test protects"
    label = report_page.VERDICT_LABEL[NOT_APPLICABLE]
    assert "not a pass" in label
    assert page.count(label) >= len(untested)
    assert f"{len(untested)} not applicable" in page


def test_a_judged_number_without_agreement_is_refused() -> None:
    with pytest.raises(report_page.NoAgreement):
        report_page.agreement_line({"supported": 18, "scored": 20, "rate": 0.9})


def test_only_a_run_the_gate_judged_against_the_live_set_counts_as_gated() -> None:
    name = "live gold+adversarial on Bedrock"
    runs: list[tuple[str, dict[str, Any]]] = [
        ("20260901T000000Z", {"gates": {"set": name, "gates": []}}),
        ("20260902T000000Z", {"gates": {"set": None, "lines": ["NOT GATED: a subset"]}}),
        ("20260903T000000Z", {"gates": {"set": "some other set", "gates": []}}),
        ("20260904T000000Z", {}),
    ]
    found = report_page.gated_live_run(name, runs)
    assert found is not None and found[0] == "20260901T000000Z"
    assert report_page.gated_live_run(name, runs[1:]) is None


def test_a_live_result_file_carries_the_verdict_the_gate_made(tmp_path: Path) -> None:
    """The page trusts stored verdicts, so the writer must store exactly what the gate returned."""
    result = run_gold_suite(default_store())
    outcome = gate(result)
    path = write_result(result, revision="test", directory=tmp_path, outcome=outcome)
    stored = json.loads(path.read_text(encoding="utf-8"))["gates"]
    assert stored == gate_record(outcome)
    assert outcome.report is not None and stored["set"] == outcome.report.set_name


def test_an_ungated_run_records_that_it_was_not_gated() -> None:
    record = gate_record(GateOutcome(report=None, lines=("NOT GATED: a subset",)))
    assert record == {"set": None, "lines": ["NOT GATED: a subset"]}


def test_the_held_out_section_states_its_run_count() -> None:
    runs = [
        (
            "20260824T120956Z",
            {
                "cases_correct": 10,
                "cases_run": 10,
                "artifact_version": "0.5.0",
                "per_case": [{"expected_refusal": True}, {"expected_refusal": True}, {}],
            },
        )
    ]
    section = report_page.heldout_section(runs, "0.7.1")
    assert "run 1 time in total" in section
    assert "The corpus is now 0.7.1" in section
    assert "moves refusal accuracy by 50 points" in section


def test_text_from_a_result_file_is_escaped() -> None:
    rows = report_page.gate_rows(
        [{"name": "<x>", "verdict": "PASS", "observed": "a&b", "expected": "<y>", "note": ""}]
    )
    cells = "".join(rows[0])
    assert "<x>" not in cells and "&lt;x&gt;" in cells and "a&amp;b" in cells
