"""Generate the corpus figures the SPA renders as prose and as the coverage panel's bars.

``web/src/corpus-facts.json`` is **generated by this module, not hand-maintained** -- decided by
sjtroxel 2026-09-05 at phase 6 step 8. It had been typed by hand and checked against the artifact by
``tests/test_corpus_facts.py``, which caught drift but only after someone introduced it. Generating it
removes the hand step entirely, the same way ``web/scripts/stage-graph.mjs`` stages the artifact and
``mark.test.ts`` regenerates ``favicon.svg``.

**Why the file exists at all, rather than the panel reading the ``done`` frame.** ``App.tsx`` records
the decision: the panel renders at first paint and never waits on a network response. Phase 5's DoD 5
keeps the artifact fetch off first paint, and sourcing these figures from the stream would smuggle one
back in. So the numbers are baked at build time from the pinned artifact.

**The ``coverage`` / ``density`` split is deliberate and mirrors a real boundary.** ``coverage`` is
``Coverage.as_dict()`` verbatim -- the **wire contract**, what ``api.app.corpus_summary()`` serves on
``/health`` and on the ``done`` frame. ``density`` is the rest of the ``Coverage`` dataclass, which
``as_dict()`` deliberately does not serialise. Collapsing the two would widen the API payload as a
side effect of tidying a file, so they stay apart.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from musical_mycelium.graph.memory import InMemoryGraphStore, artifact_directory
from musical_mycelium.graph.schema import Edge
from musical_mycelium.graph.store import Direction

#: Where the generated file lands. The SPA imports it directly, so it lives in ``web/src`` rather
#: than in ``web/public``: it is compiled into the bundle, not fetched.
FACTS_PATH = Path(__file__).resolve().parents[3] / "web" / "src" / "corpus-facts.json"

#: The header written into the file, so a reader who opens it knows it is generated and knows the
#: traps that are easy to fall into when reading these particular numbers.
COMMENT: list[str] = [
    "GENERATED FILE -- do not edit by hand. Regenerate with `make facts`.",
    "Source of truth: src/musical_mycelium/graph/facts.py, over the pinned artifact.",
    "tests/test_corpus_facts.py fails if the committed file has drifted from what the generator",
    "produces, so a corpus cut fails the build rather than a demo.",
    "",
    "These are the corpus figures the SPA RENDERS -- as copy on the first screen and as the coverage",
    "panel's bars. A number typed into a paragraph is a number that rots silently; this project has",
    "already retracted one published percentage (the 2026-08-06 77% figure, which double-counted",
    "genres credited to both the US and the UK).",
    "",
    "nodes_without_recorded_influences underwrites IMPLEMENTATION 4.5 requirement 5: a refusal must",
    "never become the negative claim 'nobody influenced X'. A large share of the corpus has no",
    "recorded influences, so a missing edge is usually not evidence of a missing influence.",
    "",
    "`coverage` is Coverage.as_dict() verbatim -- the WIRE CONTRACT, what /health and the `done`",
    "frame serve. It measures GENRES only; artist nodes are deliberately unmeasured, because P571",
    "and P495 are genre properties and one figure across both axes would let artist nodes dilute it",
    "toward zero. Its `countries` values are Wikidata P495's, which include Brixton, Hawaii,",
    "Scandinavia and Europe: the panel says PLACES, not countries, because that is what the property",
    "actually returns.",
    "",
    "`density` is the rest of the Coverage dataclass, which as_dict() does not serialise. It moved",
    "into Coverage proper at phase 6; the split from `coverage` is kept because merging them would",
    "widen the API payload as a side effect. DIRECTION MATTERS and it is this project's named failure",
    "mode: `subject influenced_by object`, so genres_without_recorded_origins counts genres that are",
    "never a SUBJECT -- the corpus records nothing about where they came from. It is not a count of",
    "genres that influenced nothing.",
]


def build(store: InMemoryGraphStore) -> dict[str, Any]:
    """The facts document for one pinned artifact."""
    # `_artifact` rather than a public accessor: this generator lives INSIDE `graph`, next to the
    # store, and needs the node list to ask a per-node question. `GraphStore` deliberately exposes no
    # node iterator -- the protocol is a query surface for the agent, not a dump -- and widening it
    # to spare one private read here would be a seam change made for a build script.
    artifact = store._artifact
    coverage = store.coverage

    # **DIRECTION. Read this twice.** ``subject influenced_by object``, so the nodes that record no
    # influences are the ones that are never a SUBJECT -- the corpus holds nothing about where they
    # came from. Counting nodes untouched by an influence edge in EITHER direction is a different
    # question with a different answer (120 rather than 723 at v0.7.1), and it is the wrong one: a
    # genre that influenced others but has no recorded origins still records no influences ON ITSELF,
    # which is what the refusal copy is about.
    #
    # This is the project's named second failure mode -- assuming the origins direction -- and it was
    # got backwards in the first draft of this generator on 2026-09-05. It is written through
    # ``Direction.INFLUENCED_BY`` rather than by filtering rows so the generator and
    # ``tests/test_corpus_facts.py`` cannot drift apart on the definition.
    #
    # Influence only, never membership: a node known solely through ``plays_genre`` still records no
    # influences, and counting membership would shrink the figure that keeps a refusal from becoming
    # the negative claim "nobody influenced X".
    without = sum(
        1 for node in artifact.nodes if not store.neighbors(node.id, Direction.INFLUENCED_BY)
    )

    return {
        "_comment": COMMENT,
        "artifact_version": store.artifact_version,
        "nodes": len(artifact.nodes),
        "nodes_without_recorded_influences": without,
        "coverage": coverage.as_dict(),
        # **Corroboration, and it is a DIFFERENT question from `verification`.** `verification` says
        # how hard ONE source was checked; this says whether a SECOND agrees. A corroborated
        # PROSE_AUTO edge is not thereby a HAND edge, and a panel showing one number where there are
        # two would be reading the opposite of the truth.
        #
        # Both counts ride together, never one alone: `reciprocal_pairs` is edges pointing both ways,
        # `contested_pairs` is edges pointing both ways FROM DIFFERENT SOURCES, and at v0.7.1 that is
        # 6 against 2. Reporting only the contested count would leave a reader unable to tell whether
        # the other four exist; reporting only the reciprocal count overcounts disagreement by 3x.
        #
        # Derived here rather than in TypeScript on purpose. The definition has one implementation,
        # in `graph/corroboration.py`; a second copy in the SPA is a second chance to drop the
        # source comparison that is the entire definition.
        "corroboration": {
            **store.corroboration,
            "contested": [
                {
                    "a": {"id": pair.a, "label": _label(store, pair.a)},
                    "b": {"id": pair.b, "label": _label(store, pair.b)},
                    "a_from_b": _side(pair.a_from_b),
                    "b_from_a": _side(pair.b_from_a),
                }
                for pair in store.contested
            ],
        },
        "density": {
            "genres_without_recorded_origins": coverage.genres_without_recorded_origins,
            "genres_with_one_connection": coverage.genres_with_one_connection,
            "busiest_genre_connections": coverage.busiest_genre_connections,
            "connections": coverage.connections,
        },
    }


def _label(store: InMemoryGraphStore, node_id: str) -> str:
    node = store.get_node(node_id)
    return node.label if node else node_id


def _side(edge: Edge) -> dict[str, Any]:
    """One direction of a disagreement, as the panel needs to state it.

    Carries `source` AND `verification` because they answer different questions and the display must
    be able to show both -- which source said it, and how hard that source was checked.
    """
    return {
        "subject_id": edge.subject_id,
        "object_id": edge.object_id,
        "source": edge.source,
        "source_id": edge.source_id,
        "verification": edge.verification,
    }


def render(store: InMemoryGraphStore) -> str:
    """The exact bytes the committed file should hold. Two-space indent, trailing newline: what
    Prettier writes, so the generated file does not fight the formatter."""
    return json.dumps(build(store), indent=2, ensure_ascii=False) + "\n"


def main() -> None:
    store = InMemoryGraphStore.from_directory(artifact_directory())
    FACTS_PATH.write_text(render(store), encoding="utf-8")
    print(f"wrote {FACTS_PATH.relative_to(Path.cwd())} for artifact v{store.artifact_version}")


if __name__ == "__main__":
    main()
